import type { Metadata } from "next";
import AdminPanelLayout from "@repo/ui/components/admin-panel/admin-panel-layout";

export const metadata: Metadata = {
  title: "Dashboard | Instafix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AdminPanelLayout>{children}</AdminPanelLayout>
  );
}
