#:schema node_modules/wrangler/config-schema.json
name = "web"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
DATABASE_URL="your_database_url_here"
DIRECT_URL="your_direct_url_here"
NEXTAUTH_SECRET="your_nextauth_secret_here"
GOOGLE_CLIENT_ID="your_google_client_id_here"
GOOGLE_CLIENT_SECRET="your_google_client_secret_here"
JWT_SECRET="your_jwt_secret_here"

# Huggingface API key
HUGGING_FACE_API_KEY="your_huggingface_api_key_here"
HUGGING_FACE_URL="your_huggingface_model_here"
HUGGING_CHATBOT_URL="your_chatbot_model_here"
HUGGING_IMAGE_CLASSIFICATION_URL="your_image_classification_model_here"

# Groq API key
GROQ_API_KEY="your_groq_api_key_here"

# Backend URL
NEXT_BACKEND_URL="http://localhost:3000"
SOCKET_SERVER_URL="ws://localhost:3001"

# MapTiler API key
MAPTILER_API_KEY="your_maptiler_api_key_here"

# R2 Cloudflare API key
R2_ENDPOINT="your_r2_endpoint_here"
R2_ACCESS_KEY_ID="your_r2_access_key_id_here"
R2_SECRET_ACCESS_KEY="your_r2_secret_access_key_here"
R2_PUBLIC_URL="your_r2_public_url_here"
R2_BUCKET_NAME="your_r2_bucket_name_here"

######## PREVIEW environment config ########
# [env.preview.vars]
# API_KEY = "your_preview_api_key_here"

######## PRODUCTION environment config ########
# [env.production.vars]
# API_KEY = "your_production_api_key_here"
