import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@repo/ui/context/ThemeContext";
import { AuthProvider } from "@/context/AuthProvider";
import { Toaster } from "@repo/ui/components/ui/sonner";
import { RecoilContextProvider } from "@/context/RecoilContextProvider";
import "@repo/ui/globals.css";
import { ChatProvider } from "@/context/ChatProvider";
import { ChatBotAi } from "@/components/chatbot/chat";
import { ReactQueryProvider } from "@/context/ReactQueryProvider";
import { FormDataProvider } from "@/context/FormDataProvider";
import { WebSocketProvider } from "@/context/WebSocketProvider";
import { FindNavbar } from "@/components/navbar/FindNavbar";
import { currentUser } from "@/lib";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <html lang="en" className="bg-background text-black dark:text-white">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <WebSocketProvider>
              <RecoilContextProvider>
                <ChatProvider>
                  <ReactQueryProvider>
                    <FormDataProvider>
                      <FindNavbar user={user} />
                      {children}
                    </FormDataProvider>
                    <ChatBotAi />
                  </ReactQueryProvider>
                </ChatProvider>
              </RecoilContextProvider>
            </WebSocketProvider>
          </AuthProvider>
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
