import type { Metadata } from "next";
import { ThemeProvider } from "@repo/ui/context/ThemeContext";
import { AuthProvider } from "@/context/AuthProvider";
import { Toaster } from "@repo/ui/components/ui/sonner";
import { RecoilContextProvider } from "@/context/RecoilContextProvider";
import "@repo/ui/globals.css";
import { ChatProvider } from "@/context/ChatProvider";
import { ReactQueryProvider } from "@/context/ReactQueryProvider";
import { FormDataProvider } from "@/context/FormDataProvider";
import { WebSocketProvider } from "@/context/WebSocketProvider";
import { FindNavbar } from "@/components/navbar/FindNavbar";
import { currentUser } from "@/lib";
import { AuthModalProvider } from "@repo/ui/context/AuthModalProvider";
import { AuthModal } from "@repo/ui/components/auth/auth-modal";
import { NavigationBar } from "@/components/navbar/NavigationBar";
import { HomeFooter } from "@/components/home/footer";
import { NotFoundProvider } from "@/context/NotFoundContext";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "InstaFix - Experts for fixing your home problems",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/favicon/favicon.ico' },
      { url: '/favicon/icon1.png' }
    ],
    apple: [
      { url: '/favicon/apple-icon.png' }
    ],
    other: [
      {
        rel: 'icon',
        url: '/favicon/icon0.svg',
        type: 'image/svg+xml'
      }
    ]
  },
  manifest: '/favicon/manifest.json',
  themeColor: '#ffffff'
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <html lang="en" className="text-black dark:text-white">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthModalProvider>
            <AuthProvider>
              <WebSocketProvider>
                <RecoilContextProvider>
                  <ChatProvider>
                    <ReactQueryProvider>
                      <FormDataProvider>
                        <NotFoundProvider>
                          <FindNavbar user={user} />
                          <NavigationBar user={user} />
                          {children}
                          <AuthModal />
                          <HomeFooter
                            className="bg-gradient-to-b relative from-yellow-500 to-yellow-900 overflow-hidden px-4 md:px-12 lg:px-24 py-10 md:py-16 "
                          />
                        </NotFoundProvider>
                      </FormDataProvider>
                    </ReactQueryProvider>
                  </ChatProvider>
                </RecoilContextProvider>
              </WebSocketProvider>
            </AuthProvider>
          </AuthModalProvider>
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
