import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Find the freelancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="px-0 sm:px-6 lg:px-24">
      {children}
    </div>
  );
}
