import { FindNavbar } from "@/components/navbar/FindNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Find the freelancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <FindNavbar />
      {children}
    </div>
  );
}
