import Footer from "@/components/posts/footer";
import Header from "@/components/posts/header";
import type { Metadata } from "next";

export const runtime = "edge";

export const metadata: Metadata = {
  title: "Create your service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div className="h-screen flex flex-col justify-between">
      <Header />
      {/* Content */}
      <div className="flex-1 p-4">
        {children}
      </div>
      <Footer />
    </div>
  );
}
