import Footer from "@/components/posts/footer";
import Header from "@/components/posts/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create your service now | Instafix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col bg-gray-50 bg-gradient-to-b from-white to-yellow-50">
      <Header />
      {children}
      <Footer />
    </div>
  );
}
